//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGServices.CGOKServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CGOKServices.ICGOKService")]
    public interface ICGOKService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGOKService/GetOKProfiles", ReplyAction="http://tempuri.org/ICGOKService/GetOKProfilesResponse")]
        CyberGlobesDM.OKDMs.OKUserDM GetOKProfiles(string token, string target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGOKService/GetOKProfiles", ReplyAction="http://tempuri.org/ICGOKService/GetOKProfilesResponse")]
        System.Threading.Tasks.Task<CyberGlobesDM.OKDMs.OKUserDM> GetOKProfilesAsync(string token, string target);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICGOKServiceChannel : CGServices.CGOKServices.ICGOKService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CGOKServiceClient : System.ServiceModel.ClientBase<CGServices.CGOKServices.ICGOKService>, CGServices.CGOKServices.ICGOKService {
        
        public CGOKServiceClient() {
        }
        
        public CGOKServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CGOKServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGOKServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGOKServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CyberGlobesDM.OKDMs.OKUserDM GetOKProfiles(string token, string target) {
            return base.Channel.GetOKProfiles(token, target);
        }
        
        public System.Threading.Tasks.Task<CyberGlobesDM.OKDMs.OKUserDM> GetOKProfilesAsync(string token, string target) {
            return base.Channel.GetOKProfilesAsync(token, target);
        }
    }
}
