//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGServices.CGTelegramServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CGTelegramServices.ICGTelegramService")]
    public interface ICGTelegramService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGTelegramService/GetTelegramProfiles", ReplyAction="http://tempuri.org/ICGTelegramService/GetTelegramProfilesResponse")]
        CyberGlobesDM.TelegramDMs.TelegramPersonDM GetTelegramProfiles(string token, string target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGTelegramService/GetTelegramProfiles", ReplyAction="http://tempuri.org/ICGTelegramService/GetTelegramProfilesResponse")]
        System.Threading.Tasks.Task<CyberGlobesDM.TelegramDMs.TelegramPersonDM> GetTelegramProfilesAsync(string token, string target);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICGTelegramServiceChannel : CGServices.CGTelegramServices.ICGTelegramService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CGTelegramServiceClient : System.ServiceModel.ClientBase<CGServices.CGTelegramServices.ICGTelegramService>, CGServices.CGTelegramServices.ICGTelegramService {
        
        public CGTelegramServiceClient() {
        }
        
        public CGTelegramServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CGTelegramServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGTelegramServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGTelegramServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CyberGlobesDM.TelegramDMs.TelegramPersonDM GetTelegramProfiles(string token, string target) {
            return base.Channel.GetTelegramProfiles(token, target);
        }
        
        public System.Threading.Tasks.Task<CyberGlobesDM.TelegramDMs.TelegramPersonDM> GetTelegramProfilesAsync(string token, string target) {
            return base.Channel.GetTelegramProfilesAsync(token, target);
        }
    }
}
