//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGServices.CGSkypeServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CGSkypeServices.ICGSkypeService")]
    public interface ICGSkypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGSkypeService/GetSkypeProfiles", ReplyAction="http://tempuri.org/ICGSkypeService/GetSkypeProfilesResponse")]
        CyberGlobesDM.SkypeDMs.SkypeFullResultDM GetSkypeProfiles(string token, string target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGSkypeService/GetSkypeProfiles", ReplyAction="http://tempuri.org/ICGSkypeService/GetSkypeProfilesResponse")]
        System.Threading.Tasks.Task<CyberGlobesDM.SkypeDMs.SkypeFullResultDM> GetSkypeProfilesAsync(string token, string target);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICGSkypeServiceChannel : CGServices.CGSkypeServices.ICGSkypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CGSkypeServiceClient : System.ServiceModel.ClientBase<CGServices.CGSkypeServices.ICGSkypeService>, CGServices.CGSkypeServices.ICGSkypeService {
        
        public CGSkypeServiceClient() {
        }
        
        public CGSkypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CGSkypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGSkypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGSkypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CyberGlobesDM.SkypeDMs.SkypeFullResultDM GetSkypeProfiles(string token, string target) {
            return base.Channel.GetSkypeProfiles(token, target);
        }
        
        public System.Threading.Tasks.Task<CyberGlobesDM.SkypeDMs.SkypeFullResultDM> GetSkypeProfilesAsync(string token, string target) {
            return base.Channel.GetSkypeProfilesAsync(token, target);
        }
    }
}
