//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGServices.CGEnrichmentServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CGEnrichmentServices.ICGEnrichmentService")]
    public interface ICGEnrichmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGEnrichmentService/InstagramAddressBook", ReplyAction="http://tempuri.org/ICGEnrichmentService/InstagramAddressBookResponse")]
        CyberGlobesDM.InstagramDMs.InstagramAddressBookDM InstagramAddressBook(string emailOrPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICGEnrichmentService/InstagramAddressBook", ReplyAction="http://tempuri.org/ICGEnrichmentService/InstagramAddressBookResponse")]
        System.Threading.Tasks.Task<CyberGlobesDM.InstagramDMs.InstagramAddressBookDM> InstagramAddressBookAsync(string emailOrPhone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICGEnrichmentServiceChannel : CGServices.CGEnrichmentServices.ICGEnrichmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CGEnrichmentServiceClient : System.ServiceModel.ClientBase<CGServices.CGEnrichmentServices.ICGEnrichmentService>, CGServices.CGEnrichmentServices.ICGEnrichmentService {
        
        public CGEnrichmentServiceClient() {
        }
        
        public CGEnrichmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CGEnrichmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGEnrichmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGEnrichmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CyberGlobesDM.InstagramDMs.InstagramAddressBookDM InstagramAddressBook(string emailOrPhone) {
            return base.Channel.InstagramAddressBook(emailOrPhone);
        }
        
        public System.Threading.Tasks.Task<CyberGlobesDM.InstagramDMs.InstagramAddressBookDM> InstagramAddressBookAsync(string emailOrPhone) {
            return base.Channel.InstagramAddressBookAsync(emailOrPhone);
        }
    }
}
